[package]
name = "similarity_cache"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/similarity_cache.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
